services:
  code-web:
    image: pgaot/code-web:latest
    ports:
      - "${PORT:-8080}:8080"
    environment:
      CODE_SQL_URL: ${CODE_SQL_URL}
      CODE_SQL_USER: ${CODE_SQL_USER}
      CODE_SQL_PASS: ${CODE_SQL_PASS}
      CODE_SQL_AUTO_DDL: ${CODE_SQL_AUTO_DDL:-true}
      YUNTOWER_APP_ID: ${YUNTOWER_APP_ID}
      YUNTOWER_APP_SECRET: ${YUNTOWER_APP_SECRET}
      CODE_AUTH_JWT_SECRET: ${CODE_AUTH_JWT_SECRET}
      CODE_AUTH_REDIS_URI: ${CODE_AUTH_REDIS_URI}
      DOC_ENABLED: ${DOC_ENABLED:-true}
    restart: unless-stopped
